name: CI
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: NPM Install
        run: npm install
      - name: NPM Install Angular
        run: npm install -g @angular/cli > /dev/null
      - name: bugfix
        run: npm install "@popperjs/core"
      - name: NPM build Angular Production
        run: ng build --configuration production
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_EC2 }}
          SOURCE: "dist/"
          REMOTE_HOST: "ec2-13-41-188-13.eu-west-2.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/html/dist/"



















